---
title: "Pengumpulan Data"
author: "Yosep Dwi Kristanto"
format: html
editor: visual
---

```{r}
#| include: false

library(tidyverse)
library(readxl)
library(countrycode)

```

## Rerata dan Variasi Skor Matematika

```{r}
#| warning: false
#| message: false

rerata_var_matematika <- read_excel("set-data/xmrlsh.xlsx", 
    sheet = "Table I.B1.2.1", skip = 8, n_max = 84) %>% 
  rename(negara = ...1,
         skor_rerata = `Mean score`,
         se_rerata = S.E....3,
         sd = S.D.,
         se_sd = S.E....5,
         skor_10 = Score...6,
         se_10 = S.E....7,
         skor_25 = Score...8,
         se_25 = S.E....9,
         skor_50 = Score...10,
         se_50 = S.E....11,
         skor_75 = Score...12,
         se_75 = S.E....13,
         skor_90 = Score...14,
         se_90 = S.E....15,
         selisih_90_10 = `Score dif.`,
         se_selisih_90_10 = S.E....17) %>% 
  filter(!negara %in% c("OECD", "Partners")) %>% 
  mutate(negara = gsub("\\*", "", negara)) %>% 
  mutate(negara = ifelse(negara == "Baku (Azerbaijan)", "Azerbaijan", ifelse(negara == "Ukrainian regions (18 of 27)", "Ukraine", ifelse(negara == "Macao (China)", "Macau", ifelse(negara == "Hong Kong (China)", "Hong Kong", ifelse(negara == "OECD average", "OECD", negara)))))
         ) %>% 
  mutate(iso3c = ifelse(negara == "Kosovo", "XKK",
                        ifelse(negara == "OECD", "ECD",
                               countrycode(negara, origin = "country.name",
                                    destination = "iso3c")))) %>% 
  relocate(iso3c, .before = negara) %>% 
  mutate(mapel = "Matematika") %>% 
  relocate(mapel, .after = negara)

head(rerata_var_matematika)

```

```{r}
#| warning: false
#| message: false

rerata_var_baca <- read_excel("set-data/xmrlsh.xlsx", 
    sheet = "Table I.B1.2.2", skip = 8, n_max = 84) %>% 
  rename(negara = ...1,
         skor_rerata = `Mean score`,
         se_rerata = S.E....3,
         sd = S.D.,
         se_sd = S.E....5,
         skor_10 = Score...6,
         se_10 = S.E....7,
         skor_25 = Score...8,
         se_25 = S.E....9,
         skor_50 = Score...10,
         se_50 = S.E....11,
         skor_75 = Score...12,
         se_75 = S.E....13,
         skor_90 = Score...14,
         se_90 = S.E....15,
         selisih_90_10 = `Score dif.`,
         se_selisih_90_10 = S.E....17) %>% 
  filter(!negara %in% c("OECD", "Partners")) %>% 
  mutate(negara = gsub("\\*", "", negara)) %>% 
  mutate(negara = ifelse(negara == "Baku (Azerbaijan)", "Azerbaijan", ifelse(negara == "Ukrainian regions (18 of 27)", "Ukraine", ifelse(negara == "Macao (China)", "Macau", ifelse(negara == "Hong Kong (China)", "Hong Kong", ifelse(negara == "OECD average", "OECD", negara)))))
         ) %>% 
  mutate(iso3c = ifelse(negara == "Kosovo", "XKK",
                        ifelse(negara == "OECD", "ECD",
                               countrycode(negara, origin = "country.name",
                                    destination = "iso3c")))) %>% 
  relocate(iso3c, .before = negara) %>% 
  mutate(mapel = "Membaca") %>% 
  relocate(mapel, .after = negara)

head(rerata_var_baca)

```

```{r}
#| warning: false
#| message: false

rerata_var_sains <- read_excel("set-data/xmrlsh.xlsx", 
    sheet = "Table I.B1.2.3", skip = 8, n_max = 84) %>% 
  rename(negara = ...1,
         skor_rerata = `Mean score`,
         se_rerata = S.E....3,
         sd = S.D.,
         se_sd = S.E....5,
         skor_10 = Score...6,
         se_10 = S.E....7,
         skor_25 = Score...8,
         se_25 = S.E....9,
         skor_50 = Score...10,
         se_50 = S.E....11,
         skor_75 = Score...12,
         se_75 = S.E....13,
         skor_90 = Score...14,
         se_90 = S.E....15,
         selisih_90_10 = `Score dif.`,
         se_selisih_90_10 = S.E....17) %>% 
  filter(!negara %in% c("OECD", "Partners")) %>% 
  mutate(negara = gsub("\\*", "", negara)) %>% 
  mutate(negara = ifelse(negara == "Baku (Azerbaijan)", "Azerbaijan", ifelse(negara == "Ukrainian regions (18 of 27)", "Ukraine", ifelse(negara == "Macao (China)", "Macau", ifelse(negara == "Hong Kong (China)", "Hong Kong", ifelse(negara == "OECD average", "OECD", negara)))))
         ) %>% 
  mutate(iso3c = ifelse(negara == "Kosovo", "XKK",
                        ifelse(negara == "OECD", "ECD",
                               countrycode(negara, origin = "country.name",
                                    destination = "iso3c")))) %>% 
  relocate(iso3c, .before = negara) %>% 
  mutate(mapel = "Sains") %>% 
  relocate(mapel, .after = negara)

head(rerata_var_sains)

```

```{r}
hasil_belajar <- rbind(rerata_var_matematika,
      rerata_var_baca,
      rerata_var_sains)

write_csv(hasil_belajar, file = "set-data/hasil_belajar.csv")
```
